#!/usr/bin/env python3
# Copyright (c) Facebook, Inc. and its affiliates.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
"""Generate fine-grained Bazel targets for Velox's core layers.

Velox's non-test sources are grouped into a few coarse layers (base, vector,
engine, functions, velox). Compiling a layer as one cc_library makes every TU's
cache key cover every header of the layer and of the layers below it, so any
header change invalidates most of Velox. This script keeps the layers as the
hand-maintained source of truth (bazel/velox_layers.bzl) and emits one target per
header and one per source file, with deps taken from each file's #includes
(bazel/velox_generated.bzl). The layer names stay as umbrella targets, so
consumers and linking are unchanged.

Run by hand after editing bazel/velox_layers.bzl or merging upstream:

    scripts/bazel/generate_velox_targets.py generate        # rewrite the .bzl
    scripts/bazel/generate_velox_targets.py generate --check # fail if stale
    scripts/bazel/generate_velox_targets.py cmake-report    # files to add/remove
    scripts/bazel/generate_velox_targets.py migrate         # one-time extraction

Velox's CMake per-library deps are not used: CMake builds Velox as one merged
library by default (VELOX_MONO_LIBRARY), so those deps are unenforced and cyclic.
"""

from __future__ import annotations

import argparse
import ast
import collections
import os
import re
import sys
from dataclasses import dataclass, field
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
ROOT_BUILD = REPO / "BUILD.bazel"
LAYERS_FILE = REPO / "bazel" / "velox_layers.bzl"
GENERATED_FILE = REPO / "bazel" / "velox_generated.bzl"
BAZEL_PACKAGE_BUILD = REPO / "bazel" / "BUILD.bazel"

LAYER_NAMES = ("base", "vector", "engine", "functions", "velox")
# List variables that only the layers use; migrate moves them with the layers.
LAYER_VARIABLES = (
    "COMPRESSION_LZ4_SRCS",
    "PARQUET_SRCS",
    "GCS_SRCS",
    "ABFS_SRCS",
    "GEO_SRCS",
    "S3_SRCS",
)

SOURCE_EXTENSIONS = (".cpp", ".cc", ".c")

# Headers produced by rules the BUILD parser cannot see through (macros).
GENERATED_INCLUDE_PREFIXES = {
    "velox/dwio/parquet/thrift/gen-cpp2/": "//:parquet_thrift_headers",
}

INCLUDE_RE = re.compile(r'^[ \t]*#[ \t]*include[ \t]*[<"]([^">]+)[">]', re.M)

GENERATED_HEADER = '''\
"""GENERATED by scripts/bazel/generate_velox_targets.py from bazel/velox_layers.bzl.

Do not edit by hand. Edit bazel/velox_layers.bzl and rerun:

    scripts/bazel/generate_velox_targets.py generate
"""
'''


# ---------------------------------------------------------------------------
# Restricted Starlark evaluation
# ---------------------------------------------------------------------------


class Unsupported(Exception):
    pass


def _glob(package_dir: Path, include, exclude=(), **_kwargs):
    found = set()
    for pattern in include:
        found.update(
            str(p.relative_to(package_dir))
            for p in package_dir.glob(pattern)
            if p.is_file()
        )
    for pattern in exclude:
        found.difference_update(
            str(p.relative_to(package_dir)) for p in package_dir.glob(pattern)
        )
    return sorted(found)


def evaluate(node: ast.AST, env: dict, package_dir: Path):
    """Evaluates the literal subset of Starlark used by BUILD and layer files.

    select() evaluates to the union of its branches, which over-approximates the
    files a configuration can see; that is the safe direction for an include index.
    """
    if isinstance(node, ast.Constant):
        return node.value
    if isinstance(node, (ast.List, ast.Tuple)):
        return [evaluate(e, env, package_dir) for e in node.elts]
    if isinstance(node, ast.Dict):
        return {
            evaluate(k, env, package_dir): evaluate(v, env, package_dir)
            for k, v in zip(node.keys, node.values)
        }
    if isinstance(node, ast.Name):
        if node.id in env:
            return env[node.id]
        raise Unsupported(f"unknown name {node.id}")
    if isinstance(node, ast.BinOp) and isinstance(node.op, ast.Add):
        return evaluate(node.left, env, package_dir) + evaluate(
            node.right, env, package_dir
        )
    if isinstance(node, ast.Call) and isinstance(node.func, ast.Name):
        args = [evaluate(a, env, package_dir) for a in node.args]
        kwargs = {k.arg: evaluate(k.value, env, package_dir) for k in node.keywords}
        if node.func.id == "dict":
            return dict(*args, **kwargs)
        if node.func.id == "glob":
            return _glob(package_dir, *args, **kwargs)
        if node.func.id == "select":
            merged = []
            for value in args[0].values():
                merged.extend(v for v in value if v not in merged)
            return merged
    raise Unsupported(ast.dump(node)[:120])


@dataclass
class Rule:
    kind: str
    package: str  # "" for the repo root
    attrs: dict
    lineno: int
    end_lineno: int

    @property
    def name(self) -> str:
        return self.attrs["name"]

    @property
    def label(self) -> str:
        return f"//{self.package}:{self.name}"


def parse_build_file(path: Path) -> tuple[list[Rule], dict]:
    """Returns top-level rule calls and module-level variables of a BUILD file.

    Attributes that use unsupported constructs are left out rather than failing,
    so the index degrades to a warning instead of breaking on unrelated rules.
    """
    package = str(path.parent.relative_to(REPO)) if path.parent != REPO else ""
    module = ast.parse(path.read_text(), filename=str(path))
    env: dict = {"True": True, "False": False, "None": None}
    rules: list[Rule] = []
    for stmt in module.body:
        if isinstance(stmt, ast.Assign) and len(stmt.targets) == 1:
            target = stmt.targets[0]
            if isinstance(target, ast.Name):
                try:
                    env[target.id] = evaluate(stmt.value, env, path.parent)
                except Unsupported:
                    pass
        elif (
            isinstance(stmt, ast.Expr)
            and isinstance(stmt.value, ast.Call)
            and isinstance(stmt.value.func, ast.Name)
        ):
            attrs = {}
            for kw in stmt.value.keywords:
                if kw.arg is None:
                    continue
                try:
                    attrs[kw.arg] = evaluate(kw.value, env, path.parent)
                except Unsupported:
                    pass
            if "name" in attrs:
                rules.append(
                    Rule(
                        stmt.value.func.id,
                        package,
                        attrs,
                        stmt.lineno,
                        stmt.end_lineno,
                    )
                )
    return rules, env


def load_layers() -> list[dict]:
    module = ast.parse(LAYERS_FILE.read_text(), filename=str(LAYERS_FILE))
    env: dict = {}
    for stmt in module.body:
        if isinstance(stmt, ast.Assign) and isinstance(stmt.targets[0], ast.Name):
            env[stmt.targets[0].id] = evaluate(stmt.value, env, REPO)
    layers = env.get("VELOX_LAYERS")
    if not layers:
        sys.exit(f"{LAYERS_FILE}: VELOX_LAYERS is missing or empty")
    unsupported = {"includes", "include_prefix", "alwayslink", "linkopts"}
    for layer in layers:
        bad = unsupported & layer.keys()
        if bad:
            sys.exit(f"layer {layer['name']}: unsupported attributes {sorted(bad)}")
    return layers


# ---------------------------------------------------------------------------
# Label helpers
# ---------------------------------------------------------------------------


def normalize_label(label: str, package: str) -> str:
    """Returns //pkg:name for in-repo labels and the label unchanged otherwise."""
    if label.startswith("@"):
        return label
    if label.startswith(":"):
        return f"//{package}{label}"
    if label.startswith("//"):
        return label if ":" in label else f"{label}:{label.rsplit('/', 1)[-1]}"
    return f"//{package}:{label}"


def local_label(label: str) -> str:
    """Spells a root-package label the way the root BUILD file does."""
    return label[2:] if label.startswith("//:") else label


def is_header(path: str) -> bool:
    return not path.endswith(SOURCE_EXTENSIONS)


# ---------------------------------------------------------------------------
# Generation
# ---------------------------------------------------------------------------


@dataclass
class FileInfo:
    path: str
    layer: str
    textual: bool
    includes: list[str] = field(default_factory=list)


class Generator:
    def __init__(self, strict: bool):
        self.strict = strict
        self.layers = {layer["name"]: layer for layer in load_layers()}
        self.warnings: dict[str, set[str]] = collections.defaultdict(set)
        self.errors: list[str] = []

        self.handwritten: dict[str, Rule] = {}  # normalized label -> rule
        self._load_handwritten_rules()
        self.files = self._load_layer_files()
        # include path -> owning label (generated groups are filled in later)
        self.index: dict[str, str] = {}
        self._index_handwritten()
        self.visible = {name: self._visible_labels(name) for name in self.layers}

    # -- inputs ------------------------------------------------------------

    def _load_handwritten_rules(self) -> None:
        build_files = [ROOT_BUILD] + sorted((REPO / "velox").rglob("BUILD.bazel"))
        for path in build_files:
            rules, _ = parse_build_file(path)
            for rule in rules:
                if rule.package == "" and rule.name in self.layers:
                    sys.exit(
                        f"BUILD.bazel still defines layer :{rule.name}; run migrate first"
                    )
                self.handwritten[rule.label] = rule
                if rule.kind == "fbthrift_library":
                    headers = Rule(
                        "cc_library",
                        rule.package,
                        {"name": rule.name + "_headers", "deps": [rule.name]},
                        rule.lineno,
                        rule.end_lineno,
                    )
                    self.handwritten[headers.label] = headers

    def _load_layer_files(self) -> dict[str, FileInfo]:
        files: dict[str, FileInfo] = {}
        for name, layer in self.layers.items():
            entries = [
                (p, False) for p in layer.get("srcs", []) + layer.get("hdrs", [])
            ]
            entries += [(p, True) for p in layer.get("textual_hdrs", [])]
            for path, textual in entries:
                if path.startswith((":", "//", "@")):
                    self.errors.append(f"layer {name}: label {path} in a file list")
                    continue
                if path in files:
                    self.errors.append(
                        f"{path} is in both layer {files[path].layer} and {name}"
                    )
                    continue
                if not (REPO / path).is_file():
                    self.errors.append(f"layer {name}: {path} does not exist")
                    continue
                files[path] = FileInfo(path, name, textual)
        for info in files.values():
            text = (REPO / info.path).read_text(errors="replace")
            info.includes = sorted(set(INCLUDE_RE.findall(text)))
        return files

    def _rule_header_paths(self, rule: Rule) -> list[str]:
        """Include paths that a hand-written rule exports."""
        if rule.kind == "cc_proto_library":
            paths = []
            for dep in rule.attrs.get("deps", []):
                proto = self.handwritten.get(normalize_label(dep, rule.package))
                for src in proto.attrs.get("srcs", []) if proto else []:
                    stem = src[: -len(".proto")]
                    base = f"{rule.package}/{stem}" if rule.package else stem
                    paths += [base + ".pb.h", base + ".pb.cc"]
            return paths
        files = [
            f
            for attr in ("hdrs", "textual_hdrs", "srcs")
            for f in rule.attrs.get(attr, [])
            if isinstance(f, str) and not f.startswith((":", "//", "@"))
        ]
        files = [f for f in files if is_header(f)]
        prefix = rule.attrs.get("include_prefix")
        strip = rule.attrs.get("strip_include_prefix", "")
        paths = []
        for f in files:
            if prefix:
                paths.append(f"{prefix}/{f}")
            else:
                full = f"{rule.package}/{f}" if rule.package else f
                if (
                    strip
                    and strip not in (".", "/")
                    and full.startswith(strip.lstrip("/") + "/")
                ):
                    full = full[len(strip.lstrip("/")) + 1 :]
                paths.append(full)
        return paths

    def _index_handwritten(self) -> None:
        for label, rule in sorted(self.handwritten.items()):
            if rule.kind not in ("cc_library", "cc_proto_library"):
                continue
            for path in self._rule_header_paths(rule):
                if path in self.files:
                    # The layer owns it; a duplicate listing elsewhere is legacy.
                    continue
                self.index.setdefault(path, label)

    def _deps_of(self, label: str) -> list[str]:
        if label.startswith("//:") and label[3:] in self.layers:
            layer = self.layers[label[3:]]
            package = ""
            deps = layer.get("deps", []) + layer.get("implementation_deps", [])
        elif label in self.handwritten:
            rule = self.handwritten[label]
            package = rule.package
            deps = rule.attrs.get("deps", []) + rule.attrs.get(
                "implementation_deps", []
            )
        else:
            return []
        return [normalize_label(d, package) for d in deps if isinstance(d, str)]

    def _visible_labels(self, layer: str) -> set[str]:
        """In-repo labels a layer could include from in the coarse graph."""
        seen: set[str] = set()
        stack = [f"//:{layer}"]
        while stack:
            label = stack.pop()
            if label in seen or label.startswith("@"):
                continue
            seen.add(label)
            stack.extend(self._deps_of(label))
        return seen

    def _visible_defines(self, layer: str) -> list[str]:
        defines: list[str] = []
        for label in sorted(self.visible[layer]):
            if label.startswith("//:") and label[3:] in self.layers:
                attrs = self.layers[label[3:]]
            elif label in self.handwritten:
                attrs = self.handwritten[label].attrs
            else:
                continue
            for d in attrs.get("defines", []):
                if d not in defines:
                    defines.append(d)
        return defines

    # -- resolution --------------------------------------------------------

    def _owner(self, path: str) -> str | None:
        if path in self.files:
            return f"file:{path}"
        if path in self.index:
            return self.index[path]
        for prefix, label in GENERATED_INCLUDE_PREFIXES.items():
            if path.startswith(prefix):
                return label
        return None

    def _resolve(self, info: FileInfo, include: str) -> str | None:
        """Returns file:<path> or a label for an include, or None if external."""
        candidates = [include]
        if not include.startswith("velox/"):
            candidates.insert(
                0, os.path.normpath(f"{os.path.dirname(info.path)}/{include}")
            )
        for candidate in candidates:
            owner = self._owner(candidate)
            if owner:
                return self._check_visible(info, candidate, owner)
        if not include.startswith("velox/"):
            return None  # Third-party header: covered by the layer's external deps.
        # Unowned or absent files are normally behind a disabled #if (feature flags,
        # Meta-internal fb/ paths). The Bazel build is the real check: with
        # layering_check, a live include of an unowned header fails to compile.
        kind = (
            "owned by no Bazel target"
            if (REPO / include).is_file()
            else "not in the tree"
        )
        self.warnings[f"#include of a file {kind} (ignored)"].add(
            f"{info.path} -> {include}"
        )
        return None

    def _check_visible(self, info: FileInfo, path: str, owner: str) -> str | None:
        """Drops edges the coarse graph could not have had.

        The coarse build compiled with layering_check, so an include of a header
        outside the layer's dependency closure is dead or preprocessor-guarded.
        Dropping it keeps the generated graph no looser than the coarse one, which
        is what guarantees it stays acyclic.
        """
        if owner.startswith("file:"):
            owner_layer = self.files[path].layer
            if (
                owner_layer == info.layer
                or f"//:{owner_layer}" in self.visible[info.layer]
            ):
                return owner
        else:
            base = owner[: -len("_headers")] if owner.endswith("_headers") else owner
            if owner in self.visible[info.layer] or base in self.visible[info.layer]:
                return owner
        self.warnings["include outside the layer's coarse dependencies (dropped)"].add(
            f"{info.path} -> {path}"
        )
        return None

    # -- graph -------------------------------------------------------------

    def build(self) -> str:
        edges: dict[str, set[str]] = {}
        label_deps: dict[str, set[str]] = {}
        for info in self.files.values():
            edges[info.path] = set()
            label_deps[info.path] = set()
            for include in info.includes:
                owner = self._resolve(info, include)
                if owner is None:
                    continue
                if owner.startswith("file:"):
                    target = owner[5:]
                    if not is_header(target):
                        self.errors.append(
                            f"{info.path} includes source file {target}; list it as a textual header"
                        )
                    elif target != info.path:
                        edges[info.path].add(target)
                else:
                    label_deps[info.path].add(owner)
        if self.errors:
            self._fail()

        headers = sorted(p for p in self.files if is_header(p))
        groups = strongly_connected(headers, {p: edges[p] for p in headers})
        group_of: dict[str, str] = {}
        group_members: dict[str, list[str]] = {}
        for members in groups:
            members = sorted(members)
            layers = {self.files[m].layer for m in members}
            if len(layers) > 1:
                self.errors.append(
                    f"include cycle spans layers {sorted(layers)}: {members}"
                )
            label = f"//:hdr/{members[0]}"
            group_members[label] = members
            for m in members:
                group_of[m] = label
        if self.errors:
            self._fail()

        targets: list[dict] = []
        for label, members in sorted(group_members.items()):
            layer = self.files[members[0]].layer
            deps = set()
            for m in members:
                deps |= {group_of[e] for e in edges[m]} | label_deps[m]
            deps.discard(label)
            targets.append(
                {
                    "name": label[3:],
                    "layer": layer,
                    "hdrs": [m for m in members if not self.files[m].textual],
                    "textual_hdrs": [m for m in members if self.files[m].textual],
                    "deps": sorted(deps),
                }
            )
        for path in sorted(p for p in self.files if not is_header(p)):
            info = self.files[path]
            deps = {group_of[e] for e in edges[path]} | label_deps[path]
            targets.append(
                {
                    "name": f"src/{path}",
                    "layer": info.layer,
                    "srcs": [path],
                    "deps": sorted(deps),
                }
            )
        self._self_check(targets)
        return self._render(targets)

    def _self_check(self, targets: list[dict]) -> None:
        names = collections.Counter(t["name"] for t in targets)
        names.update(list(self.layers))
        dupes = [n for n, c in names.items() if c > 1]
        clashes = [n for n in names if f"//:{n}" in self.handwritten]
        covered = {
            f
            for t in targets
            for attr in ("hdrs", "textual_hdrs", "srcs")
            for f in t.get(attr, [])
        }
        missing = set(self.files) - covered
        graph = {
            t["name"]: {d[3:] for d in t["deps"] if d.startswith("//:hdr/")}
            for t in targets
        }
        cycles = [c for c in strongly_connected(sorted(graph), graph) if len(c) > 1]
        for problem, items in (
            ("duplicate target names", dupes),
            ("names clash with hand-written targets", clashes),
            ("files missing from generated targets", sorted(missing)),
            ("dependency cycles", cycles),
        ):
            if items:
                self.errors.append(f"{problem}: {items[:10]}")
        if self.errors:
            self._fail()

    # -- output ------------------------------------------------------------

    def _render(self, targets: list[dict]) -> str:
        out = [
            GENERATED_HEADER,
            'load("@rules_cc//cc:cc_library.bzl", "cc_library")',
            "",
        ]
        layer_consts = {}
        for name in sorted(self.layers):
            layer = self.layers[name]
            const = f"_{name.upper()}"
            layer_consts[name] = const
            external = sorted(
                {
                    d
                    for d in layer.get("deps", [])
                    + layer.get("implementation_deps", [])
                    if d.startswith("@")
                }
            )
            out.append(f"# Third-party deps every file of layer :{name} may use.")
            out.append(f"{const}_EXTERNAL_DEPS = {fmt_list(external, 0)}")
            out.append("")
            out.append(
                f"# Defines layer :{name} saw as one cc_library (its own and lower layers')."
            )
            out.append(f"{const}_DEFINES = {fmt_list(self._visible_defines(name), 0)}")
            out.append("")

        out.append("def velox_generated_targets():")
        out.append(
            '    """Declares the per-file Velox targets and the layer umbrellas."""'
        )
        for t in targets:
            layer = self.layers[t["layer"]]
            const = layer_consts[t["layer"]]
            attrs = [("name", fmt_str(t["name"]))]
            for attr in ("srcs", "hdrs", "textual_hdrs"):
                if t.get(attr):
                    attrs.append((attr, fmt_list(t[attr], 8)))
            for attr in ("copts", "cxxopts"):
                if layer.get(attr):
                    attrs.append((attr, fmt_list(layer[attr], 8)))
            attrs.append(("local_defines", f"{const}_DEFINES"))
            if "hdrs" in t or "textual_hdrs" in t:
                attrs.append(
                    (
                        "strip_include_prefix",
                        fmt_str(layer.get("strip_include_prefix", ".")),
                    )
                )
            if layer.get("features"):
                attrs.append(("features", fmt_list(layer["features"], 8)))
            if layer.get("tags"):
                attrs.append(("tags", fmt_list(layer["tags"], 8)))
            attrs.append(("visibility", '["//visibility:private"]'))
            deps = [local_label(d) for d in t["deps"]]
            attrs.append(("deps", f"{fmt_list(deps, 8)} + {const}_EXTERNAL_DEPS"))
            out.append(fmt_call("cc_library", attrs))

        for name in sorted(self.layers):
            layer = self.layers[name]
            members = [f":{t['name']}" for t in targets if t["layer"] == name]
            # layering_check only accepts an include if the including target
            # directly depends on a target listing the header. Consumers depend on
            # the umbrella, so it lists every layer header too. As textual headers
            # they are not parsed a second time.
            headers = sorted(
                f
                for t in targets
                if t["layer"] == name
                for f in t.get("hdrs", []) + t.get("textual_hdrs", [])
            )
            attrs = [("name", fmt_str(name))]
            attrs.append(("textual_hdrs", fmt_list(headers, 8)))
            if layer.get("defines"):
                attrs.append(("defines", fmt_list(layer["defines"], 8)))
            # An umbrella only aggregates its members, so DWYU would report every
            # member as an unused dep.
            tags = sorted(set(layer.get("tags", [])) | {"no-dwyu"})
            attrs.append(("tags", fmt_list(tags, 8)))
            attrs.append(
                (
                    "strip_include_prefix",
                    fmt_str(layer.get("strip_include_prefix", ".")),
                )
            )
            if layer.get("implementation_deps"):
                attrs.append(
                    ("implementation_deps", fmt_list(layer["implementation_deps"], 8))
                )
            attrs.append(("deps", fmt_list(members + list(layer.get("deps", [])), 8)))
            out.append(
                f"    # Umbrella for layer :{name}; linking and propagated defines match the old target."
            )
            out.append(fmt_call("cc_library", attrs))
        return "\n".join(out).rstrip() + "\n"

    def _fail(self) -> None:
        self.report_warnings()
        for e in self.errors:
            print(f"error: {e}", file=sys.stderr)
        sys.exit(1)

    def report_warnings(self, verbose: bool = False) -> None:
        for kind, items in sorted(self.warnings.items()):
            print(f"warning: {len(items)} x {kind}", file=sys.stderr)
            for item in sorted(items)[: None if verbose else 8]:
                print(f"    {item}", file=sys.stderr)
            if not verbose and len(items) > 8:
                print("    ... (use --verbose for all)", file=sys.stderr)
        if self.strict and self.warnings:
            sys.exit("error: warnings are fatal with --strict")


def strongly_connected(nodes: list[str], edges: dict[str, set[str]]) -> list[list[str]]:
    """Tarjan's algorithm, iterative so deep include chains don't recurse."""
    index: dict[str, int] = {}
    low: dict[str, int] = {}
    stack: list[str] = []
    on_stack: set[str] = set()
    result: list[list[str]] = []
    counter = 0
    for root in nodes:
        if root in index:
            continue
        work = [(root, iter(sorted(edges.get(root, ()))))]
        index[root] = low[root] = counter
        counter += 1
        stack.append(root)
        on_stack.add(root)
        while work:
            node, children = work[-1]
            advanced = False
            for child in children:
                if child not in index:
                    index[child] = low[child] = counter
                    counter += 1
                    stack.append(child)
                    on_stack.add(child)
                    work.append((child, iter(sorted(edges.get(child, ())))))
                    advanced = True
                    break
                if child in on_stack:
                    low[node] = min(low[node], index[child])
            if advanced:
                continue
            work.pop()
            if work:
                parent = work[-1][0]
                low[parent] = min(low[parent], low[node])
            if low[node] == index[node]:
                component = []
                while True:
                    member = stack.pop()
                    on_stack.discard(member)
                    component.append(member)
                    if member == node:
                        break
                result.append(component)
    return result


def fmt_str(s: str) -> str:
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def fmt_list(items: list[str], indent: int) -> str:
    if not items:
        return "[]"
    if len(items) == 1:
        return f"[{fmt_str(items[0])}]"
    pad = " " * (indent + 4)
    body = "".join(f"{pad}{fmt_str(i)},\n" for i in items)
    return "[\n" + body + " " * indent + "]"


def fmt_call(fn: str, attrs: list[tuple[str, str]]) -> str:
    lines = [f"    {fn}("]
    lines += [f"        {k} = {v}," for k, v in attrs]
    lines.append("    )")
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# migrate
# ---------------------------------------------------------------------------


def migrate() -> None:
    if LAYERS_FILE.exists():
        sys.exit(f"{LAYERS_FILE} already exists; migrate runs once")
    text = ROOT_BUILD.read_text()
    lines = text.splitlines(keepends=True)
    module = ast.parse(text)

    spans: list[tuple[int, int, str, str | None]] = []  # start, end, kind, name
    for stmt in module.body:
        if (
            isinstance(stmt, ast.Assign)
            and isinstance(stmt.targets[0], ast.Name)
            and stmt.targets[0].id in LAYER_VARIABLES
        ):
            spans.append((stmt.lineno, stmt.end_lineno, "var", stmt.targets[0].id))
        elif (
            isinstance(stmt, ast.Expr)
            and isinstance(stmt.value, ast.Call)
            and getattr(stmt.value.func, "id", None) == "cc_library"
        ):
            name = next(
                (
                    ast.literal_eval(k.value)
                    for k in stmt.value.keywords
                    if k.arg == "name"
                ),
                None,
            )
            if name in LAYER_NAMES:
                spans.append((stmt.lineno, stmt.end_lineno, "layer", name))
    found = {name for _, _, kind, name in spans if kind == "layer"}
    if found != set(LAYER_NAMES):
        sys.exit(f"expected layers {LAYER_NAMES}, found {sorted(found)}")

    # Extend each span upward over its attached comment block.
    extended = []
    for start, end, kind, name in sorted(spans):
        while start > 1 and lines[start - 2].lstrip().startswith("#"):
            start -= 1
        extended.append((start, end, kind, name))

    out = [
        '"""The core Velox layers, as data.\n\n'
        "Nothing in Bazel loads this file. scripts/bazel/generate_velox_targets.py\n"
        "reads it and writes bazel/velox_generated.bzl, which declares one target\n"
        "per header and source file plus an umbrella per layer. Edit the lists here\n"
        "and rerun the script.\n"
        '"""\n\n'
    ]
    order = []
    for start, end, kind, name in extended:
        block = "".join(lines[start - 1 : end])
        if kind == "layer":
            const = f"_{name.upper()}"
            block = re.sub(
                r"^cc_library\(", f"{const} = dict(", block, count=1, flags=re.M
            )
            order.append(const)
        out.append(block.rstrip("\n") + "\n\n")
    out.append("VELOX_LAYERS = [\n" + "".join(f"    {c},\n" for c in order) + "]\n")

    first_layer_start = min(s for s, _, kind, _ in extended if kind == "layer")
    removed = set()
    for start, end, _, _ in extended:
        removed.update(range(start, end + 1))
        # Drop one blank separator line after the block.
        if end < len(lines) and not lines[end].strip():
            removed.add(end + 1)
    new_lines = []
    for number, line in enumerate(lines, start=1):
        if number == first_layer_start:
            new_lines.append(
                "# The core layers (base, vector, engine, functions, velox) are declared\n"
                "# per file from bazel/velox_layers.bzl. Edit that file and run\n"
                "# scripts/bazel/generate_velox_targets.py generate.\n"
                "velox_generated_targets()\n\n"
            )
        if number not in removed:
            new_lines.append(line)
    new_text = "".join(new_lines)
    load_line = 'load("//bazel:velox_generated.bzl", "velox_generated_targets")\n'
    new_text = new_text.replace('load("@fbthrift//', load_line + 'load("@fbthrift//', 1)
    if load_line not in new_text:
        sys.exit("could not find where to add the load statement")

    LAYERS_FILE.parent.mkdir(exist_ok=True)
    LAYERS_FILE.write_text("".join(out))
    if not BAZEL_PACKAGE_BUILD.exists():
        BAZEL_PACKAGE_BUILD.write_text(
            "# Package for the Velox layer definitions and their generated targets.\n"
        )
    ROOT_BUILD.write_text(new_text)
    print(f"wrote {LAYERS_FILE.relative_to(REPO)}; updated BUILD.bazel")


# ---------------------------------------------------------------------------
# cmake-report
# ---------------------------------------------------------------------------

CMAKE_SKIP_DIR = re.compile(
    r"(^|/)(tests?|benchmarks?|fuzzer|experimental|examples|tool)(/|$)"
)
CMAKE_KEYWORDS = {"OBJECT", "STATIC", "SHARED", "INTERFACE", "PUBLIC", "PRIVATE"}


def cmake_commands(text: str):
    """Yields (command, args) with comments stripped and ${VAR} left in place."""
    text = re.sub(r"#\[\[.*?\]\]", "", text, flags=re.S)
    text = re.sub(r'#[^\n"]*', "", text)
    for match in re.finditer(r"([A-Za-z_][A-Za-z0-9_]*)\s*\(", text):
        depth, i = 1, match.end()
        while i < len(text) and depth:
            depth += {"(": 1, ")": -1}.get(text[i], 0)
            i += 1
        body = text[match.end() : i - 1]
        yield match.group(1).lower(), re.findall(r'"[^"]*"|[^\s"]+', body)


def cmake_files() -> dict[str, str]:
    """Maps each non-test file listed by Velox's CMake to its CMake library.

    Both branches of every if() are taken, so feature-gated files are included;
    the report says where they are so Chalk's choices can be checked against it.
    """
    files: dict[str, str] = {}
    for cmake in sorted((REPO / "velox").rglob("CMakeLists.txt")):
        rel_dir = cmake.parent.relative_to(REPO)
        if CMAKE_SKIP_DIR.search(str(rel_dir)):
            continue
        variables: dict[str, list[str]] = collections.defaultdict(list)

        def expand(arg: str) -> list[str]:
            arg = arg.strip('"')
            m = re.fullmatch(r"\$\{(\w+)\}", arg)
            if m:
                return list(variables.get(m.group(1), []))
            return [arg] if "$" not in arg else []

        for command, args in cmake_commands(cmake.read_text()):
            if command == "set" and args:
                variables[args[0]] = [v for a in args[1:] for v in expand(a)]
            elif command == "list" and len(args) > 2 and args[0] == "APPEND":
                variables[args[1]] += [v for a in args[2:] for v in expand(a)]
            elif command in ("velox_add_library", "velox_sources") and args:
                library = args[0]
                for arg in args[1:]:
                    for value in expand(arg):
                        if value in CMAKE_KEYWORDS or value == "HEADERS":
                            continue
                        if not re.search(r"\.(cpp|cc|c|h|hpp|inc)$", value):
                            continue
                        path = os.path.normpath(str(rel_dir / value))
                        if (REPO / path).is_file():
                            files.setdefault(path, library)
    return files


def cmake_report(verbose: bool) -> None:
    layers = load_layers()
    in_layers = {
        p
        for layer in layers
        for attr in ("srcs", "hdrs", "textual_hdrs")
        for p in layer.get(attr, [])
    }
    owned = set(in_layers)
    for path in [ROOT_BUILD] + sorted((REPO / "velox").rglob("BUILD.bazel")):
        rules, _ = parse_build_file(path)
        for rule in rules:
            pkg = f"{rule.package}/" if rule.package else ""
            for attr in ("srcs", "hdrs", "textual_hdrs"):
                owned.update(
                    pkg + f
                    for f in rule.attrs.get(attr, [])
                    if isinstance(f, str) and not f.startswith((":", "//", "@"))
                )
    cmake = cmake_files()

    def show(title: str, paths: list[str]) -> None:
        print(f"\n{title}: {len(paths)}")
        by_dir = collections.Counter(os.path.dirname(p) for p in paths)
        if verbose:
            for p in paths:
                print(f"    {p}  ({cmake.get(p, '-')})")
        else:
            for d, n in sorted(by_dir.items()):
                print(f"    {n:4}  {d}/")

    show(
        "In Velox CMake but in no Bazel target (new upstream files, or features Chalk leaves off)",
        sorted(set(cmake) - owned),
    )
    show(
        "In a layer but listed by no CMake library (Chalk-only, or removed upstream)",
        sorted(p for p in in_layers if p not in cmake),
    )
    missing = sorted(p for p in in_layers if not (REPO / p).is_file())
    show("In a layer but missing on disk (must be removed from the layer)", missing)


# ---------------------------------------------------------------------------


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    sub = parser.add_subparsers(dest="command", required=True)
    gen = sub.add_parser("generate", help="write bazel/velox_generated.bzl")
    gen.add_argument("--check", action="store_true", help="fail if the file is stale")
    gen.add_argument("--strict", action="store_true", help="treat warnings as errors")
    gen.add_argument("--verbose", action="store_true", help="list every warning")
    sub.add_parser("migrate", help="one-time: move the layers out of BUILD.bazel")
    report = sub.add_parser("cmake-report", help="compare layers with Velox's CMake")
    report.add_argument("--verbose", action="store_true", help="list every file")
    args = parser.parse_args()

    if args.command == "migrate":
        migrate()
    elif args.command == "cmake-report":
        cmake_report(args.verbose)
    else:
        generator = Generator(strict=args.strict)
        content = generator.build()
        generator.report_warnings(args.verbose)
        if args.check:
            current = GENERATED_FILE.read_text() if GENERATED_FILE.exists() else ""
            if current != content:
                sys.exit(f"{GENERATED_FILE.relative_to(REPO)} is stale; rerun generate")
            print("up to date")
            return
        GENERATED_FILE.write_text(content)
        n_targets = content.count("    cc_library(")
        print(f"wrote {GENERATED_FILE.relative_to(REPO)}: {n_targets} targets")


if __name__ == "__main__":
    main()
